input-file: /Users/joel/Projects/OpenAssessItToolkit/opendiffit/example/file-list_january-february_diffed.csv
output-file: /Users/joel/Projects/OpenAssessItToolkit/opendiffit/example/file-list_january-february_diffed_detected.csv
